version: '3.8'

services:
  playwright-mcp:
    build:
      context: .
      dockerfile: Dockerfile.playwright
    container_name: playwright-mcp-server
    ports:
      - "9222:9222"
    environment:
      - DISPLAY=:99
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
      - PLAYWRIGHT_CHROMIUM_ARGS=--no-sandbox --disable-dev-shm-usage --disable-setuid-sandbox
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./downloads:/app/downloads
    stdin_open: true
    tty: true
    networks:
      - playwright-network

networks:
  playwright-network:
    driver: bridge